# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("background-color: #0D1B2A")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.widget = QtWidgets.QWidget(self.page_home)
        self.widget.setGeometry(QtCore.QRect(10, 10, 781, 441))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 1, 2, 1, 1)
        self.btn_rishe_fel = QtWidgets.QPushButton(self.widget)
        self.btn_rishe_fel.setMinimumSize(QtCore.QSize(300, 101))
        self.btn_rishe_fel.setMaximumSize(QtCore.QSize(999, 999))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn_rishe_fel.setFont(font)
        self.btn_rishe_fel.setMouseTracking(False)
        self.btn_rishe_fel.setTabletTracking(False)
        self.btn_rishe_fel.setStyleSheet("background-color: #000; color: #fff; padding: 0px;\n"
"border-radius: 12px;\n"
"border-style: solid;\n"
"border-color: #6096B4;\n"
"border-width: 2px 2px 2px 2px;")
        self.btn_rishe_fel.setObjectName("btn_rishe_fel")
        self.gridLayout_2.addWidget(self.btn_rishe_fel, 2, 2, 1, 1)
        self.btn_naghsh_dastory = QtWidgets.QPushButton(self.widget)
        self.btn_naghsh_dastory.setMinimumSize(QtCore.QSize(200, 101))
        self.btn_naghsh_dastory.setMaximumSize(QtCore.QSize(999, 999))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn_naghsh_dastory.setFont(font)
        self.btn_naghsh_dastory.setMouseTracking(False)
        self.btn_naghsh_dastory.setTabletTracking(False)
        self.btn_naghsh_dastory.setStyleSheet("background-color: #000; color: #fff; padding: 0px;\n"
"border-radius: 12px;\n"
"border-style: solid;\n"
"border-color: #6096B4;\n"
"border-width: 2px 2px 2px 2px;")
        self.btn_naghsh_dastory.setObjectName("btn_naghsh_dastory")
        self.gridLayout_2.addWidget(self.btn_naghsh_dastory, 0, 2, 1, 1)
        self.btn_bakhsbandi = QtWidgets.QPushButton(self.widget)
        self.btn_bakhsbandi.setMinimumSize(QtCore.QSize(300, 101))
        self.btn_bakhsbandi.setMaximumSize(QtCore.QSize(999, 999))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn_bakhsbandi.setFont(font)
        self.btn_bakhsbandi.setMouseTracking(False)
        self.btn_bakhsbandi.setTabletTracking(False)
        self.btn_bakhsbandi.setStyleSheet("background-color: #000; color: #fff; padding: 0px;\n"
"border-radius: 12px;\n"
"border-style: solid;\n"
"border-color: #6096B4;\n"
"border-width: 2px 2px 2px 2px;")
        self.btn_bakhsbandi.setObjectName("btn_bakhsbandi")
        self.gridLayout_2.addWidget(self.btn_bakhsbandi, 0, 0, 1, 1)
        self.btn_mofrad = QtWidgets.QPushButton(self.widget)
        self.btn_mofrad.setMinimumSize(QtCore.QSize(300, 101))
        self.btn_mofrad.setMaximumSize(QtCore.QSize(999, 999))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn_mofrad.setFont(font)
        self.btn_mofrad.setMouseTracking(False)
        self.btn_mofrad.setTabletTracking(False)
        self.btn_mofrad.setStyleSheet("background-color: #000; color: #fff; padding: 0px;\n"
"border-radius: 12px;\n"
"border-style: solid;\n"
"border-color: #6096B4;\n"
"border-width: 2px 2px 2px 2px;")
        self.btn_mofrad.setObjectName("btn_mofrad")
        self.gridLayout_2.addWidget(self.btn_mofrad, 2, 0, 1, 1)
        self.btn_mani = QtWidgets.QPushButton(self.widget)
        self.btn_mani.setMinimumSize(QtCore.QSize(300, 101))
        self.btn_mani.setMaximumSize(QtCore.QSize(999, 999))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn_mani.setFont(font)
        self.btn_mani.setMouseTracking(False)
        self.btn_mani.setTabletTracking(False)
        self.btn_mani.setStyleSheet("background-color: #000; color: #fff; padding: 0px;\n"
"border-radius: 12px;\n"
"border-style: solid;\n"
"border-color: #6096B4;\n"
"border-width: 2px 2px 2px 2px;")
        self.btn_mani.setObjectName("btn_mani")
        self.gridLayout_2.addWidget(self.btn_mani, 4, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 3, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_home)
        self.page_bakhsgbandi = QtWidgets.QWidget()
        self.page_bakhsgbandi.setObjectName("page_bakhsgbandi")
        self.lineEdit_naghsh = QtWidgets.QLineEdit(self.page_bakhsgbandi)
        self.lineEdit_naghsh.setGeometry(QtCore.QRect(332, 20, 461, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_naghsh.setFont(font)
        self.lineEdit_naghsh.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_naghsh.setText("")
        self.lineEdit_naghsh.setObjectName("lineEdit_naghsh")
        self.btn_javab_naghsh = QtWidgets.QPushButton(self.page_bakhsgbandi)
        self.btn_javab_naghsh.setGeometry(QtCore.QRect(150, 20, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_javab_naghsh.setFont(font)
        self.btn_javab_naghsh.setStyleSheet("#btn_javab_naghsh{\n"
"background-color:#198754;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid #198754;\n"
"border-radius: 7px;\n"
"}\n"
"#btn_javab_naghsh:hover{\n"
"background-color: #157448;\n"
"border:2x sloid#5cb85c;\n"
"}")
        self.btn_javab_naghsh.setObjectName("btn_javab_naghsh")
        self.back_1 = QtWidgets.QPushButton(self.page_bakhsgbandi)
        self.back_1.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.back_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_1.setStyleSheet("border:none;\n"
"color:rgb(255, 255, 255)")
        self.back_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/back-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_1.setIcon(icon)
        self.back_1.setIconSize(QtCore.QSize(45, 45))
        self.back_1.setObjectName("back_1")
        self.result_naghsh = QtWidgets.QLabel(self.page_bakhsgbandi)
        self.result_naghsh.setGeometry(QtCore.QRect(20, 110, 761, 471))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.result_naghsh.setFont(font)
        self.result_naghsh.setStyleSheet("background-color: #0D1B2A;\n"
"color: rgb(255, 255, 255);")
        self.result_naghsh.setText("")
        self.result_naghsh.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.result_naghsh.setObjectName("result_naghsh")
        self.stackedWidget.addWidget(self.page_bakhsgbandi)
        self.page_bakhshbandi = QtWidgets.QWidget()
        self.page_bakhshbandi.setObjectName("page_bakhshbandi")
        self.lineEdit_bakhsh = QtWidgets.QLineEdit(self.page_bakhshbandi)
        self.lineEdit_bakhsh.setGeometry(QtCore.QRect(322, 20, 471, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_bakhsh.setFont(font)
        self.lineEdit_bakhsh.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_bakhsh.setText("")
        self.lineEdit_bakhsh.setObjectName("lineEdit_bakhsh")
        self.btn_javab_bakhsh = QtWidgets.QPushButton(self.page_bakhshbandi)
        self.btn_javab_bakhsh.setGeometry(QtCore.QRect(140, 20, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_javab_bakhsh.setFont(font)
        self.btn_javab_bakhsh.setStyleSheet("#btn_javab_bakhsh{\n"
"background-color:#198754;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid #198754;\n"
"border-radius: 7px;\n"
"}\n"
"#btn_javab_bakhsh:hover{\n"
"background-color: #157448;\n"
"border:2x sloid#5cb85c;\n"
"}")
        self.btn_javab_bakhsh.setObjectName("btn_javab_bakhsh")
        self.back_2 = QtWidgets.QPushButton(self.page_bakhshbandi)
        self.back_2.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.back_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_2.setStyleSheet("border:none;\n"
"color:rgb(255, 255, 255)")
        self.back_2.setText("")
        self.back_2.setIcon(icon)
        self.back_2.setIconSize(QtCore.QSize(45, 45))
        self.back_2.setObjectName("back_2")
        self.result_bakhsh = QtWidgets.QLabel(self.page_bakhshbandi)
        self.result_bakhsh.setGeometry(QtCore.QRect(20, 110, 761, 471))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.result_bakhsh.setFont(font)
        self.result_bakhsh.setStyleSheet("background-color: #0D1B2A;\n"
"color: rgb(255, 255, 255);")
        self.result_bakhsh.setText("")
        self.result_bakhsh.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.result_bakhsh.setObjectName("result_bakhsh")
        self.stackedWidget.addWidget(self.page_bakhshbandi)
        self.page_risheye_fel = QtWidgets.QWidget()
        self.page_risheye_fel.setObjectName("page_risheye_fel")
        self.btn_javab_fel = QtWidgets.QPushButton(self.page_risheye_fel)
        self.btn_javab_fel.setGeometry(QtCore.QRect(130, 20, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_javab_fel.setFont(font)
        self.btn_javab_fel.setStyleSheet("#btn_javab_fel{\n"
"background-color:#198754;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid #198754;\n"
"border-radius: 7px;\n"
"}\n"
"#btn_javab_fel:hover{\n"
"background-color: #157448;\n"
"border:2x sloid#5cb85c;\n"
"}")
        self.btn_javab_fel.setObjectName("btn_javab_fel")
        self.lineEdit_fel = QtWidgets.QLineEdit(self.page_risheye_fel)
        self.lineEdit_fel.setGeometry(QtCore.QRect(310, 20, 481, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_fel.setFont(font)
        self.lineEdit_fel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.lineEdit_fel.setText("")
        self.lineEdit_fel.setObjectName("lineEdit_fel")
        self.back_3 = QtWidgets.QPushButton(self.page_risheye_fel)
        self.back_3.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.back_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_3.setStyleSheet("border:none;\n"
"color:rgb(255, 255, 255)")
        self.back_3.setText("")
        self.back_3.setIcon(icon)
        self.back_3.setIconSize(QtCore.QSize(45, 45))
        self.back_3.setObjectName("back_3")
        self.result_fel = QtWidgets.QLabel(self.page_risheye_fel)
        self.result_fel.setGeometry(QtCore.QRect(20, 110, 761, 471))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.result_fel.setFont(font)
        self.result_fel.setStyleSheet("background-color: #0D1B2A;\n"
"color: rgb(255, 255, 255);")
        self.result_fel.setText("")
        self.result_fel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.result_fel.setObjectName("result_fel")
        self.stackedWidget.addWidget(self.page_risheye_fel)
        self.page_mofrad = QtWidgets.QWidget()
        self.page_mofrad.setObjectName("page_mofrad")
        self.btn_javab_mofrad = QtWidgets.QPushButton(self.page_mofrad)
        self.btn_javab_mofrad.setGeometry(QtCore.QRect(130, 20, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_javab_mofrad.setFont(font)
        self.btn_javab_mofrad.setStyleSheet("#btn_javab_mofrad{\n"
"background-color:#198754;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid #198754;\n"
"border-radius: 7px;\n"
"}\n"
"#btn_javab_mofrad:hover{\n"
"background-color: #157448;\n"
"border:2x sloid#5cb85c;\n"
"}")
        self.btn_javab_mofrad.setObjectName("btn_javab_mofrad")
        self.lineEdit_mofrad = QtWidgets.QLineEdit(self.page_mofrad)
        self.lineEdit_mofrad.setGeometry(QtCore.QRect(312, 20, 481, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_mofrad.setFont(font)
        self.lineEdit_mofrad.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.lineEdit_mofrad.setText("")
        self.lineEdit_mofrad.setObjectName("lineEdit_mofrad")
        self.back_4 = QtWidgets.QPushButton(self.page_mofrad)
        self.back_4.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.back_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_4.setStyleSheet("border:none;\n"
"color:rgb(255, 255, 255)")
        self.back_4.setText("")
        self.back_4.setIcon(icon)
        self.back_4.setIconSize(QtCore.QSize(45, 45))
        self.back_4.setObjectName("back_4")
        self.result_mofrad = QtWidgets.QLabel(self.page_mofrad)
        self.result_mofrad.setGeometry(QtCore.QRect(20, 110, 761, 471))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.result_mofrad.setFont(font)
        self.result_mofrad.setStyleSheet("background-color: #0D1B2A;\n"
"color: rgb(255, 255, 255);")
        self.result_mofrad.setText("")
        self.result_mofrad.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.result_mofrad.setObjectName("result_mofrad")
        self.stackedWidget.addWidget(self.page_mofrad)
        self.page_mani = QtWidgets.QWidget()
        self.page_mani.setObjectName("page_mani")
        self.btn_javab_mani = QtWidgets.QPushButton(self.page_mani)
        self.btn_javab_mani.setGeometry(QtCore.QRect(130, 20, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_javab_mani.setFont(font)
        self.btn_javab_mani.setStyleSheet("#btn_javab_mani{\n"
"background-color:#198754;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid #198754;\n"
"border-radius: 7px;\n"
"}\n"
"#btn_javab_mani:hover{\n"
"background-color: #157448;\n"
"border:2x sloid#5cb85c;\n"
"}")
        self.btn_javab_mani.setObjectName("btn_javab_mani")
        self.lineEdit_mani = QtWidgets.QLineEdit(self.page_mani)
        self.lineEdit_mani.setGeometry(QtCore.QRect(312, 20, 481, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_mani.setFont(font)
        self.lineEdit_mani.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.lineEdit_mani.setText("")
        self.lineEdit_mani.setObjectName("lineEdit_mani")
        self.result_mani = QtWidgets.QLabel(self.page_mani)
        self.result_mani.setGeometry(QtCore.QRect(20, 110, 761, 471))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.result_mani.setFont(font)
        self.result_mani.setStyleSheet("background-color: #0D1B2A;\n"
"color: rgb(255, 255, 255);")
        self.result_mani.setText("")
        self.result_mani.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.result_mani.setObjectName("result_mani")
        self.back_5 = QtWidgets.QPushButton(self.page_mani)
        self.back_5.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.back_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_5.setStyleSheet("border:none;\n"
"color:rgb(255, 255, 255)")
        self.back_5.setText("")
        self.back_5.setIcon(icon)
        self.back_5.setIconSize(QtCore.QSize(45, 45))
        self.back_5.setObjectName("back_5")
        self.stackedWidget.addWidget(self.page_mani)
        self.page_emla = QtWidgets.QWidget()
        self.page_emla.setObjectName("page_emla")
        self.back_6 = QtWidgets.QPushButton(self.page_emla)
        self.back_6.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.back_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_6.setStyleSheet("border:none;\n"
"color:rgb(255, 255, 255)")
        self.back_6.setText("")
        self.back_6.setIcon(icon)
        self.back_6.setIconSize(QtCore.QSize(45, 45))
        self.back_6.setObjectName("back_6")
        self.result_emla = QtWidgets.QLabel(self.page_emla)
        self.result_emla.setGeometry(QtCore.QRect(20, 110, 761, 471))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.result_emla.setFont(font)
        self.result_emla.setStyleSheet("background-color: #0D1B2A;\n"
"color: rgb(255, 255, 255);")
        self.result_emla.setText("")
        self.result_emla.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.result_emla.setObjectName("result_emla")
        self.lineEdit_darsa_emla = QtWidgets.QLineEdit(self.page_emla)
        self.lineEdit_darsa_emla.setGeometry(QtCore.QRect(290, 20, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_darsa_emla.setFont(font)
        self.lineEdit_darsa_emla.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.lineEdit_darsa_emla.setText("")
        self.lineEdit_darsa_emla.setObjectName("lineEdit_darsa_emla")
        self.btn_javab_emla = QtWidgets.QPushButton(self.page_emla)
        self.btn_javab_emla.setGeometry(QtCore.QRect(90, 20, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_javab_emla.setFont(font)
        self.btn_javab_emla.setStyleSheet("#btn_javab_emla{\n"
"background-color:#198754;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid #198754;\n"
"border-radius: 7px;\n"
"}\n"
"#btn_javab_emlai:hover{\n"
"background-color: #157448;\n"
"border:2x sloid#5cb85c;\n"
"}")
        self.btn_javab_emla.setObjectName("btn_javab_emla")
        self.lineEdit_paye_emla = QtWidgets.QLineEdit(self.page_emla)
        self.lineEdit_paye_emla.setGeometry(QtCore.QRect(550, 20, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_paye_emla.setFont(font)
        self.lineEdit_paye_emla.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.lineEdit_paye_emla.setText("")
        self.lineEdit_paye_emla.setObjectName("lineEdit_paye_emla")
        self.stackedWidget.addWidget(self.page_emla)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_rishe_fel.setText(_translate("MainWindow", "ریشه فعل"))
        self.btn_naghsh_dastory.setText(_translate("MainWindow", "نقش دستوری"))
        self.btn_bakhsbandi.setText(_translate("MainWindow", "بخش بندی"))
        self.btn_mofrad.setText(_translate("MainWindow", "مفرد"))
        self.btn_mani.setText(_translate("MainWindow", "معنی کلمات"))
        self.btn_javab_naghsh.setText(_translate("MainWindow", "جواب"))
        self.btn_javab_bakhsh.setText(_translate("MainWindow", "جواب"))
        self.btn_javab_fel.setText(_translate("MainWindow", "جواب"))
        self.lineEdit_fel.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.lineEdit_fel.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_javab_mofrad.setText(_translate("MainWindow", "جواب"))
        self.lineEdit_mofrad.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.lineEdit_mofrad.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_javab_mani.setText(_translate("MainWindow", "جواب"))
        self.lineEdit_mani.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.lineEdit_mani.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.lineEdit_darsa_emla.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.lineEdit_darsa_emla.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_javab_emla.setText(_translate("MainWindow", "جواب"))
        self.lineEdit_paye_emla.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.lineEdit_paye_emla.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
from . import resources_rc
